---
title: "Exploratory Data Analysis"
author: "Giles Carlos"
date: "2023-04-09"
output: html_document
---

```{r}
library(dplyr)
library(readr)
library(ggplot2)

post_injury <- read_csv(here::here("data/post_injury.csv"))
```

```{r}
# Box Plot
post_injury

post_injury %>% 
  mutate(type = case_when(type == "w" ~ "Wildtype", 
                          type == "k" ~ "Knock-out",
                          type == "v" ~ "Vehicle")) %>% 
  ggplot(aes(x = type, y = ave_bad)) + 
  geom_boxplot() + 
  labs(x = "Type of Mice", y = "Average # Errors", title = "Distribution of Ladder Beam Performance Across Mice Groups") + 
  theme_classic()

post_injury %>% 
  group_by(type) %>% 
  summarise(group_avg = mean(ave_bad),
            group_sum = sum(ave_bad)) %>% 
  ggplot(aes(x = type, y = group_avg)) +
  geom_bar(stat = "identity") +
  labs(x = "Type of Mice", y = "Average # Errors", title = "Average Ladder Beam Performance Across Mice Groups") + 
  theme_classic()
```

# EDA for DLC Training Data

```{r}
library(ggpubr)
library(jpeg)
library(png)
library(gridExtra)

dlc_train <- read_csv(here::here("data/dlc_train_example_video.csv"))

frame <- readPNG(here::here("data/images/img0924.png"))

track_paws1<- dlc_train %>% 
  filter(frame == "img0924.png") %>% 
  mutate(bodypart = case_when(bodypart == "back_left_paw" ~ "Back Left Paw",
                   bodypart == "back_right_paw" ~ "Back Right Paw",
                   bodypart == "front_left_paw" ~ "Front Left Paw",
                   bodypart == "front_right_paw" ~ "Front Right Paw",
                   bodypart == "nose" ~ "Nose",
                   bodypart == "tail" ~ "Tail", 
                   bodypart == "front_mid" ~ "Front Middle",
                   bodypart == "back_mid" ~ "Back Middle")) %>% 
  ggplot(aes(x = x, y = y, color = bodypart)) + 
  background_image(frame) +
  geom_point(size = 1.5) +
  ylim(3840, 0) + 
  xlim(0, 2160) +  
  labs(x = "X",
       y = "Y", 
       color = "Body Part") + 
  theme(legend.position = "none")

track_paws2 <- dlc_train %>% 
  filter(bodypart %in% c("back_left_paw", "back_right_paw", "front_left_paw", "front_right_paw")) %>% 
  mutate(bodypart = case_when(bodypart == "back_left_paw" ~ "Back Left Paw",
                   bodypart == "back_right_paw" ~ "Back Right Paw",
                   bodypart == "front_left_paw" ~ "Front Left Paw",
                   bodypart == "front_right_paw" ~ "Front Right Paw")) %>% 

  ggplot(aes(x = x, y = y, color = bodypart)) + 
  geom_point() +
  ylim(3840, 0) + 
  xlim(0, 2160) + 
  labs(x = "X",
       y = "Y", 
       color = "Body Part") + 
  theme(legend.position = c(0.25, 0.875),
        legend.key.size = unit(0.25, 'cm'))

grid.arrange(track_paws1, track_paws2, ncol = 2)
```






