---
title: "Cleaning and Extracting Post Injury Data"
author: "Giles Carlos"
date: "2023-04-06"
output: html_document
---

# Libraries

```{r}
library(dplyr)
library(tidyr)
library(xlsx)
library(readr)
library(readxl)
library(stringr)
```

# Summary Data

```{r}
# Loading in data and cleaning names
post_injury <- read.xlsx(file = here::here("data/A111.1 Ladder Beam Post-Injury.xls"), 
                         sheetName = "Summary", 
                         rowIndex = 6:36, 
                         colIndex = 3:9) %>% 
  janitor::clean_names() %>% 
  rename(total_good = total_good_l_r_3_runs,
         total_bad = total_bad_l_r_3_runs)

# Adding column for type of mice
# w - wildtype
# k - knock-out
# v - vehicle
post_injury <- post_injury %>% 
  mutate(type = case_when(
    animal %in% c("1", "3", "8", "10", "10*(10)", "13", "15", "20", "22", "25", "27", "31", "32") ~ "w",
    animal %in% c("2", "4", "7", "9", "14", "16", "19", "21", "26", "28") ~ "k",
    animal %in% c("5", "6", "11", "10(11)", "12", "17", "18", "23", "24", "29", "30") ~ "v"))

# selecting appropriate categories
post_injury <- 
  post_injury %>% 
  select(animal, total_good, total_bad, ave_good, ave_bad, lb_score, type)
  
# writing new csv to data folder
write_csv(post_injury, here::here("data/post_injury.csv"))
```

# Data From Each Sheet (Individual Mice)

```{r}
# Accessing sheet names of the post-injury excel file
sheet <- excel_sheets(here::here("data/A111.1 Ladder Beam Post-Injury.xls"))
sheet <- sheet[-1] # removing summary sheet
  
# Function that extracts information on right and left bad steps for all three trials for all mice
extract_sheet <- function(f, sht) {
  # Getting animal ID
  id <- read_excel(f, 
           sheet = sht,
           col_names = FALSE,
           range = "C5")
  colnames(id) <- "animal" # adding appropriate column name
  id$animal <- as.character(id$animal) # making all type char
  
  # Getting misstep information
  data <- read_excel(f, 
             sheet = sht,
             col_names = FALSE,
             col_types = c("numeric","numeric", "skip", "skip", "skip", "numeric","numeric", "skip", "skip", "skip", "numeric","numeric"),
             range = "C69:N69")
  
  colnames(data) <- c('right_bad','left_bad', 'right_bad','left_bad', 'right_bad','left_bad') # renaming columns
  data <- rbind(data[1, 1:2], data[1, 3:4], data[1, 5:6]) # taking every two columns and appending them as rows
  cbind(id, data) # combining animal id and misstep info
}

# create list of data frames, one for each mouse
list_data_frame <- lapply(setNames(sheet, sheet), 
                     function(x) extract_sheet(here::here("data/A111.1 Ladder Beam Post-Injury.xls"), sht = x))

# combine data frames into one
raw_post_injury <- bind_rows(list_data_frame)
raw_post_injury$total = raw_post_injury$left_bad + raw_post_injury$right_bad
raw_post_injury$pct_bad = raw_post_injury$total / 100

raw_post_injury <- raw_post_injury %>% 
  mutate(type = case_when(
    animal %in% c("1", "3", "8", "10", "10*(10)", "13", "15", "20", "22", "25", "27", "31", "32") ~ "w",
    animal %in% c("2", "4", "7", "9", "14", "16", "19", "21", "26", "28") ~ "k",
    animal %in% c("5", "6", "11", "10(11)", "12", "17", "18", "23", "24", "29", "30") ~ "v"))

# export to csv
write_csv(raw_post_injury, here::here("data/raw_post_injury.csv"))
```

# Training Data from DLC

```{r}
dlc_train <- read_csv(here::here("data/train/DLC Example Train Data-Giles-2023-04-26/labeled-data/MVI_8324/CollectedData_Giles.csv"),
                      col_names = TRUE,
                      skip = 1) 
dlc_train <- dlc_train[,-1]

dlc_train <- 
  dlc_train %>% 
  rename(video = `...2`,
         frame = `...3`,
         front_left_paw_x = `bodypart1...4`,
         front_left_paw_y = `bodypart1...5`,
         front_right_paw_x = `bodypart2...6`,
         front_right_paw_y = `bodypart2...7`,
         back_left_paw_x = `bodypart3...8`,
         back_left_paw_y = `bodypart3...9`,
         back_right_paw_x = `objectA...10`,
         back_right_paw_y = `objectA...11`) 

dlc_train <- dlc_train[-1,]

dlc_train %>% 
  pivot_longer(-c(video, frame), 
               names_to = c("bodypart", ".value"),
               names_sep = "w_") %>% 
  mutate(bodypart = as.factor(paste(bodypart, "w", sep="")),
         x = as.numeric(x),
         y = as.numeric(y)) 

write_csv(dlc_train, here::here("data/dlc_train_example_video.csv"))
```






